build:
  version: "3.0"

cards:
  message: "Welcome to NexusBank cards related local APIs "
  contactDetails:
    name: "Naveen - Developer"
    email: "naveen@nexusbank.com"
  onCallSupport:
    - (555) 555-1234
    - (555) 523-1345
